### ISSUE TITLE
Doubts about multi-GPU training.

### ISSUE THREAD

**Issue by yfreedomliTHU** [luizgh/avc_nips_2018#1]
Hi, @luizgh  , I'm very interested in your work at CVPR2019, and I attempt to use it in the competition. However, when I was training with multiple GPUs, I found that although multiple GPUs were specified, only one GPU was working. In contrast to your implementation in CVPR2019 open source code, there may be a small mistake in your code.

In line 177:utils.requires_grad_(model.model, False) and line 189  utils.requires_grad_(model.model, True) of train_tiny_imagenet_ddn.py, I think it will be better to replace model.model with model.

My torch  is version:1.0.1,and the code requires >= 0.4.1.

**Comment by jeromerony** [comment]
Hi, thanks for the interest in our work.

The way we added multi-gpu training is far from ideal as it takes every available GPU that the script can see using `DataParallel`. The problem might come from you environment variables that allow the script to only see one GPU of your system (check with `echo $CUDA_VISIBLE_DEVICES`).

About the requires_grad_, it is intended to use the function on model.model as the model is a [NormalizedModel](https://github.com/luizgh/avc_nips_2018/blob/ab0243375a43cf532a66994e2c88a3a3f8ef7001/train_tiny_imagenet_ddn.py#L76) object in which we do not want to train the mean and std. So the requires_grad_ attribute is changed only for the parameters of the actual model.

**Comment by yfreedomliTHU** [comment]
Hi, @jeromerony ,Thank you very much for your explanation, and I have a deeper understanding of the code. Actually, I attempted to change **utils.requires_grad_(model.model, False)** because of the AttributeError: **'DataParallel' object has no attribute 'model'**.
I'm not sure if it's a pytorch version issue. Maybe model.module.model will be better?Thanks.

**Comment by jeromerony** [comment]
Hmm, that is indeed a problem. Originally, the training loop was in the main function and requires_grad_ was called on `m` rather than `model.model` which made it compatible with the module coming from DataParallel. Since then, I did not re-test on multi-GPU when putting the training loop in a separate function.
There are several ways of solving that but the fact that the we need to through `module` if there are several GPUs makes it dirty and I think it's best not to use `DataParallel` if training only on one GPU. The simplest way I see is to pass `m` to the train function.
